name: expense_tracker_v2
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fl_chart: ^1.1.1
  drift: ^2.29.0
  sqlite3_flutter_libs: ^0.5.40
  path_provider: ^2.1.5
  path: ^1.9.1
  get_it: ^9.1.0
  provider: ^6.1.5+1
  intl: ^0.20.2
  google_fonts: ^6.3.2
  shared_preferences: ^2.5.3
  file_picker: ^10.3.7
  excel: ^4.0.6
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  drift_dev: ^2.29.0
  build_runner: ^2.10.4

flutter:

 uses-material-design: true

